[build]
  publish = "html/"  # S채g 책t Netlify att anv채nda html/-mappen som publish directory

[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true  # Tvingar redirect 채ven om filer finns[^1][^7]